/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import modelo.Tentativas;
import modelo.interfaces.ObservadorTentativa;

/**
 *
 * @author aluno
 */
public class PainelPartida extends javax.swing.JPanel implements ObservadorTentativa, ActionListener {

    /**
     * Creates new form PainelPartida
     */
    public PainelPartida() {
        initComponents();
    }
    
    public void setTentativas(Tentativas t){
        if(t == null)
            throw new IllegalArgumentException("A tentativa não pode ser nula");
        t.registrarObservador(this);
        atualizar(t);
    }

    @Override
    public void atualizar(Tentativas t) {
        ntentativas.setText("" + t.atual());
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novaPalavra = new javax.swing.JButton();
        tentativas = new javax.swing.JLabel();
        ntentativas = new javax.swing.JLabel();

        novaPalavra.setText("Nova Palavra");

        tentativas.setText("Tentativas:");

        ntentativas.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tentativas)
                .addGap(2, 2, 2)
                .addComponent(ntentativas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novaPalavra)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(novaPalavra)
                .addComponent(tentativas)
                .addComponent(ntentativas))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton novaPalavra;
    private javax.swing.JLabel ntentativas;
    private javax.swing.JLabel tentativas;
    // End of variables declaration//GEN-END:variables

    
}
